<?php
/*
 * Create custom post type
 * */
add_action('init', 'init_post_types');
function init_post_types()
{
    register_post_type('partner', array(
        'label' => null,
        'labels' => array(
            'name' => 'Партнери',
            'singular_name' => 'Партнер',
            'add_new' => 'Додати партнера',
            'add_new_item' => 'Додати нового партнера',
            'edit_item' => 'Редагувати партнера',
            'new_item' => 'Новий партнер',
            'view_item' => 'Перегляд партнера',
            'search_items' => 'Пошук партнера',
            'not_found' => 'Не знайдено партнера',
            'not_found_in_trash' => 'В кошику не знайдено партнерів',
            'parent_item_colon' => '',
            'menu_name' => 'Партнери',
        ),
        'description' => '',
        'public' => true,
        'publicly_queryable' => false,
        'exclude_from_search' => false,
        'show_ui' => true,
        'show_in_menu' => true,
        'show_in_admin_bar' => true,
        'show_in_nav_menus' => true,
        'show_in_rest' => true,
        'rest_base' => null,
        'menu_position' => 4,
        'hierarchical' => false,
        'supports' => array('title', 'thumbnail', 'excerpt'),
        'taxonomies' => array(),
        'has_archive' => false,
        'query_var' => false,
        'menu_icon' => 'dashicons-rest-api',
    ));

    register_post_type('news', array(
        'label' => null,
        'labels' => array(
            'name' => 'Новини',
            'singular_name' => 'Новина',
            'add_new' => 'Додати новину',
            'add_new_item' => 'Додати нову новину',
            'edit_item' => 'Редагувати новину',
            'new_item' => 'Створити новину',
            'view_item' => 'Перегляд новини',
            'search_items' => 'Пошук новин',
            'not_found' => 'Не знайдено новин',
            'not_found_in_trash' => 'В кошику не знайдено новин',
            'parent_item_colon' => '',
            'menu_name' => 'Новини',
        ),
        'description' => '',
        'public' => true,
        'publicly_queryable' => true,
        'exclude_from_search' => false,
        'show_ui' => true,
        'show_in_menu' => true,
        'show_in_admin_bar' => true,
        'show_in_nav_menus' => true,
        'show_in_rest' => true,
        'rest_base' => null,
        'menu_position' => 4,
        'hierarchical' => false,
        'supports' => array('title', 'thumbnail', 'excerpt'),
        'taxonomies' => array(),
        'has_archive' => false,
        'rewrite' => array('slug' => 'news/%news-category%', 'with_front' => false),
        'query_var' => false,
        'menu_icon' => 'dashicons-admin-page',
    ));

    register_post_type('story', array(
        'label' => null,
        'labels' => array(
            'name' => 'Історії',
            'singular_name' => 'Історія',
            'add_new' => 'Додати історію',
            'add_new_item' => 'Додати нову історію',
            'edit_item' => 'Редагувати історію',
            'new_item' => 'Створити історію',
            'view_item' => 'Перегляд історії',
            'search_items' => 'Пошук історій',
            'not_found' => 'Не знайдено історій',
            'not_found_in_trash' => 'В кошику не знайдено історій',
            'parent_item_colon' => '',
            'menu_name' => 'Історії',
        ),
        'description' => '',
        'public' => true,
        'publicly_queryable' => true,
        'exclude_from_search' => false,
        'show_ui' => true,
        'show_in_menu' => true,
        'show_in_admin_bar' => true,
        'show_in_nav_menus' => true,
        'show_in_rest' => true,
        'rest_base' => null,
        'menu_position' => 4,
        'hierarchical' => false,
        'supports' => array('title', 'thumbnail', 'excerpt'),
        'taxonomies' => array(),
        'has_archive' => false,
        'rewrite' => array('slug' => 'story/%story-category%', 'with_front' => false),
        'query_var' => false,
        'menu_icon' => 'dashicons-format-status',
    ));

    register_post_type('people', array(
        'label' => null,
        'labels' => array(
            'name' => 'Люди',
            'singular_name' => 'Людина',
            'add_new' => 'Додати людину',
            'add_new_item' => 'Додати нову людину',
            'edit_item' => 'Редагувати людину',
            'new_item' => 'Створити людину',
            'view_item' => 'Перегляд людей',
            'search_items' => 'Пошук людей',
            'not_found' => 'Не знайдено людей',
            'not_found_in_trash' => 'В кошику не знайдено людей',
            'parent_item_colon' => '',
            'menu_name' => 'Люди',
        ),
        'description' => '',
        'public' => true,
        'publicly_queryable' => false,
        'exclude_from_search' => false,
        'show_ui' => true,
        'show_in_menu' => true,
        'show_in_admin_bar' => true,
        'show_in_nav_menus' => true,
        'show_in_rest' => true,
        'rest_base' => null,
        'menu_position' => 4,
        'hierarchical' => false,
        'supports' => array('title', 'thumbnail', 'excerpt'),
        'taxonomies' => array(),
        'has_archive' => false,
        'rewrite' => array('slug' => 'people/%people-category%', 'with_front' => false),
        'query_var' => false,
        'menu_icon' => 'dashicons-groups',
    ));

    register_post_type('case', array(
        'label' => null,
        'labels' => array(
            'name' => 'Кейси',
            'singular_name' => 'Кейс',
            'add_new' => 'Додати кейс',
            'add_new_item' => 'Додати новий кейс',
            'edit_item' => 'Редагувати кейс',
            'new_item' => 'Створити кейс',
            'view_item' => 'Перегляд кейсу',
            'search_items' => 'Пошук кейсів',
            'not_found' => 'Не знайдено кейсів',
            'not_found_in_trash' => 'В кошику не знайдено кейсів',
            'parent_item_colon' => '',
            'menu_name' => 'Кейси',
        ),
        'description' => '',
        'public' => true,
        'publicly_queryable' => true,
        'exclude_from_search' => false,
        'show_ui' => true,
        'show_in_menu' => true,
        'show_in_admin_bar' => true,
        'show_in_nav_menus' => true,
        'show_in_rest' => true,
        'rest_base' => null,
        'menu_position' => 4,
        'hierarchical' => false,
        'supports' => array('title', 'thumbnail', 'excerpt'),
        'taxonomies' => array(),
        'has_archive' => false,
        'query_var' => false,
        'menu_icon' => 'dashicons-welcome-learn-more',
    ));

    register_post_type('review', array(
        'label' => null,
        'labels' => array(
            'name' => 'Відгуки',
            'singular_name' => 'Відгук',
            'add_new' => 'Додати відгук',
            'add_new_item' => 'Додати новий відгук',
            'edit_item' => 'Редагувати відгук',
            'new_item' => 'Новий відгук',
            'view_item' => 'Переглянути відгук',
            'search_items' => 'Пошук відгуків',
            'not_found' => 'Не знайдено відгуків',
            'not_found_in_trash' => 'В кошику не знайдено відгуків',
            'parent_item_colon' => '',
            'menu_name' => 'Відгуки',
        ),
        'description' => '',
        'public' => true,
        'publicly_queryable' => false,
        'exclude_from_search' => false,
        'show_ui' => true,
        'show_in_menu' => true,
        'show_in_admin_bar' => true,
        'show_in_nav_menus' => true,
        'show_in_rest' => true,
        'rest_base' => null,
        'menu_position' => 4,
        'hierarchical' => false,
        'supports' => array('title', 'thumbnail', 'excerpt'),
        'taxonomies' => array(),
        'has_archive' => false,
        'query_var' => false,
        'menu_icon' => 'dashicons-format-chat',
    ));

    register_post_type('vacancy', array(
        'label' => null,
        'labels' => array(
            'name' => 'Вакансії',
            'singular_name' => 'Вакансія',
            'add_new' => 'Додати вакансію',
            'add_new_item' => 'Додати нову вакансію',
            'edit_item' => 'Редагувати вакансію',
            'new_item' => 'Створити вакансію',
            'view_item' => 'Перегляд вакансії',
            'search_items' => 'Пошук вакансій',
            'not_found' => 'Не знайдено вакансій',
            'not_found_in_trash' => 'В кошику не знайдено вакансій',
            'parent_item_colon' => '',
            'menu_name' => 'Вакансії',
        ),
        'description' => '',
        'public' => true,
        'publicly_queryable' => true,
        'exclude_from_search' => false,
        'show_ui' => true,
        'show_in_menu' => true,
        'show_in_admin_bar' => true,
        'show_in_nav_menus' => true,
        'show_in_rest' => true,
        'rest_base' => null,
        'menu_position' => 4,
        'hierarchical' => false,
        'supports' => array('title', 'excerpt'),
        'taxonomies' => array(),
        'has_archive' => false,
        'rewrite' => array('slug' => 'vacancy/%vacancy-city%', 'with_front' => false),
        'query_var' => false,
        'menu_icon' => 'dashicons-id-alt',
    ));

    register_post_type('report', array(
        'label' => null,
        'labels' => array(
            'name' => 'Звіти',
            'singular_name' => 'Звіт',
            'add_new' => 'Додати звіт',
            'add_new_item' => 'Додати новий звіт',
            'edit_item' => 'Редагувати звіт',
            'new_item' => 'Новий звіт',
            'view_item' => 'Переглянути звіт',
            'search_items' => 'Пошук звітів',
            'not_found' => 'Не знайдено звітів',
            'not_found_in_trash' => 'В кошику не знайдено звітів',
            'parent_item_colon' => '',
            'menu_name' => 'Звіти',
        ),
        'description' => '',
        'public' => true,
        'publicly_queryable' => false,
        'exclude_from_search' => false,
        'show_ui' => true,
        'show_in_menu' => true,
        'show_in_admin_bar' => true,
        'show_in_nav_menus' => true,
        'show_in_rest' => true,
        'rest_base' => null,
        'menu_position' => 4,
        'hierarchical' => false,
        'supports' => array('title', 'excerpt'),
        'taxonomies' => array(),
        'has_archive' => false,
        'query_var' => false,
        'menu_icon' => 'dashicons-chart-bar',
    ));

    register_post_type('question', array(
        'label' => null,
        'labels' => array(
            'name' => 'Поширені питання',
            'singular_name' => 'Питання',
            'add_new' => 'Додати питання',
            'add_new_item' => 'Додати нове питання',
            'edit_item' => 'Редагувати питання',
            'new_item' => 'Нове питання',
            'view_item' => 'Переглянути питання',
            'search_items' => 'Пошук питань',
            'not_found' => 'Не знайдено питань',
            'not_found_in_trash' => 'В кошику не знайдено питань',
            'parent_item_colon' => '',
            'menu_name' => 'Поширені питання',
        ),
        'description' => '',
        'public' => true,
        'publicly_queryable' => false,
        'exclude_from_search' => false,
        'show_ui' => true,
        'show_in_menu' => true,
        'show_in_admin_bar' => true,
        'show_in_nav_menus' => true,
        'show_in_rest' => true,
        'rest_base' => null,
        'menu_position' => 4,
        'hierarchical' => false,
        'supports' => array('title', 'editor'),
        'taxonomies' => array('question-category'),
        'has_archive' => false,
        'query_var' => false,
        'menu_icon' => 'dashicons-info',
        'template' => [
            ['t4u/simple-text', []]
        ],
        'template_lock' => false,
    ));
}
