<?php
/*
 * Create custom post type
 * */
add_action('init', 'init_post_types');
function init_post_types()
{
    register_post_type('partner', array(
        'label' => null,
        'labels' => array(
            'name' => 'Партнери',
            'singular_name' => 'Партнер',
            'add_new' => 'Додати партнера',
            'add_new_item' => 'Додати нового партнера',
            'edit_item' => 'Редагувати партнера',
            'new_item' => 'Новий партнер',
            'view_item' => 'Перегляд партнера',
            'search_items' => 'Пошук партнера',
            'not_found' => 'Не знайдено партнера',
            'not_found_in_trash' => 'В кошику не знайдено партнерів',
            'parent_item_colon' => '',
            'menu_name' => 'Партнери',
        ),
        'description' => '',
        'public' => true,
        'publicly_queryable' => false,
        'exclude_from_search' => false,
        'show_ui' => true,
        'show_in_menu' => true,
        'show_in_admin_bar' => true,
        'show_in_nav_menus' => true,
        'show_in_rest' => true,
        'rest_base' => null,
        'menu_position' => 4,
        'hierarchical' => false,
        'supports' => array('title', 'thumbnail', 'excerpt'),
        'taxonomies' => array(),
        'has_archive' => false,
        'query_var' => false,
        'menu_icon' => 'dashicons-groups',
    ));

    register_post_type('news', array(
        'label' => null,
        'labels' => array(
            'name' => 'Новини',
            'singular_name' => 'Новина',
            'add_new' => 'Додати новину',
            'add_new_item' => 'Додати нову новину',
            'edit_item' => 'Редагувати новину',
            'new_item' => 'Створити новину',
            'view_item' => 'Перегляд новини',
            'search_items' => 'Пошук новин',
            'not_found' => 'Не знайдено новин',
            'not_found_in_trash' => 'В кошику не знайдено новин',
            'parent_item_colon' => '',
            'menu_name' => 'Новини',
        ),
        'description' => '',
        'public' => true,
        'publicly_queryable' => true,
        'exclude_from_search' => false,
        'show_ui' => true,
        'show_in_menu' => true,
        'show_in_admin_bar' => true,
        'show_in_nav_menus' => true,
        'show_in_rest' => true,
        'rest_base' => null,
        'menu_position' => 4,
        'hierarchical' => false,
        'supports' => array('title', 'thumbnail', 'excerpt'),
        'taxonomies' => array(),
        'has_archive' => false,
        'rewrite' => array('slug' => 'news/%news-category%', 'with_front' => false ),
        'query_var' => false,
        'menu_icon' => 'dashicons-admin-page',
    ));

    register_post_type('story', array(
        'label' => null,
        'labels' => array(
            'name' => 'Історії',
            'singular_name' => 'Історія',
            'add_new' => 'Додати історію',
            'add_new_item' => 'Додати нову історію',
            'edit_item' => 'Редагувати історію',
            'new_item' => 'Створити історію',
            'view_item' => 'Перегляд історії',
            'search_items' => 'Пошук історій',
            'not_found' => 'Не знайдено історій',
            'not_found_in_trash' => 'В кошику не знайдено історій',
            'parent_item_colon' => '',
            'menu_name' => 'Історії',
        ),
        'description' => '',
        'public' => true,
        'publicly_queryable' => true,
        'exclude_from_search' => false,
        'show_ui' => true,
        'show_in_menu' => true,
        'show_in_admin_bar' => true,
        'show_in_nav_menus' => true,
        'show_in_rest' => true,
        'rest_base' => null,
        'menu_position' => 4,
        'hierarchical' => false,
        'supports' => array('title', 'thumbnail', 'excerpt'),
        'taxonomies' => array(),
        'has_archive' => false,
        'rewrite' => array('slug' => 'story/%story-category%', 'with_front' => false ),
        'query_var' => false,
        'menu_icon' => 'dashicons-format-status',
    ));
}